Código/Teste Estágio/Models/ErrorViewModel.cs
namespace Teste_Estágio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Código/Teste Estágio/Models/HomeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Teste_Estágio.Models
{
    public class HomeModel
    {

    }
}

Código/Teste Estágio/Models/MaterialModel.cs
namespace Teste_Estágio.Models
{
    public class MaterialModel : MaterialsModel
    {
        public List<SuppliersModel>? ListaSuppliers { get; set; }
    }
}

Código/Teste Estágio/Models/MaterialsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Teste_Estágio.Models
{
    public class MaterialsModel
    {
        [Key]
        public int Id { get; set; }        
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FiscalCode { get; set; }
        public string Specie { get; set; }
        public DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? UpdatedBy { get; set; }
        public int SupplierId { get; set; }
        public SuppliersModel Supplier { get; set; }




    }
}

Código/Teste Estágio/Models/SuppliersModel.cs
using System.ComponentModel.DataAnnotations;

namespace Teste_Estágio.Models
{
    public class SuppliersModel
    {
        [Key]
        public required int Id { get; set; } // Propriedade com chave primária
        public required string Name { get; set; } // Propriedades mapeáveis
        public required string Description { get; set; }
        public required string CNPJ { get; set; }
        public required int CEP { get; set; }
        public required string Address { get; set; }
        public required string RegistrationDay { get; set; }        
        public required string QrCode { get; set; }

        public String toString()
        {
            String [] dados = QrCode.Split('%');
            String QrCodeFormatado;

            QrCodeFormatado = dados[0];
            for(int i = 1; i < dados.Length; i++)
            {
                QrCodeFormatado = QrCodeFormatado + dados[i];
            }
            return QrCodeFormatado;
        }

        
    }
        
    
}

Código/Teste Estágio/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Teste_Estágio.Models;

namespace Teste_Estágio.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Material()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Código/Teste Estágio/Controllers/MaterialController.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Teste_Estágio.Context;
using Teste_Estágio.Models;
using Teste_Estágio.Repositorio;

namespace Teste_Estágio.Controllers;


public class MaterialController : Controller
{
    private readonly IMaterialRepositorio _materialRepositorio;
    private readonly ISupplierRepositorio _supplierRepositorio;
    private readonly BancoContext _context;
    public MaterialController(IMaterialRepositorio materialRepositorio, BancoContext contexto)
    {
        _materialRepositorio = materialRepositorio;
        _context = contexto;
    }

    

    public IActionResult Index()
    {

        List<MaterialsModel> materials = _materialRepositorio.searchEveryItem();
        return View(materials);
    }

    public IActionResult Create()
    {
        var suppliers = _context.Supplier.ToList(); // Obtenha os fornecedores do banco de dados
        var model = new MaterialModel();
        {
            model.ListaSuppliers = suppliers;
        };
        return View(model);
    }


    public IActionResult Edit(int id)
    {
        MaterialsModel material = _materialRepositorio.searchForId(id);
        return View(material);
    }
    public IActionResult Delete(int id)
    {
        _materialRepositorio.Delete(id);
        return RedirectToAction("Index");
    }

    public IActionResult ConfirmDelete(int id)
    {
        MaterialsModel material = _materialRepositorio.searchForId(id);
        return View(material);
    }

    [HttpPost]
    public IActionResult Create(MaterialsModel material)
    {
        material.CreatedAt = DateTime.Now;
        material.UpdatedAt = DateTime.Now;
        material.UpdatedBy = material.CreatedBy;
        _materialRepositorio.add(material);        
        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Change(MaterialsModel material)
    {
        _materialRepositorio.Update(material);
        return RedirectToAction("Index");
    }

}

Código/Teste Estágio/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using Teste_Estágio.Models;
using Teste_Estágio.Repositorio;

namespace Teste_Estágio.Controllers
{
    public class SupplierController : Controller
    {
        private readonly ISupplierRepositorio _supplierRepositorio;
        public SupplierController(ISupplierRepositorio supplierRepositorio)
        {
            _supplierRepositorio = supplierRepositorio;
        }
        public IActionResult Index()
        {
            List<SuppliersModel> suppliers = _supplierRepositorio.searchEveryItem();
            return View(suppliers);
        }

        public IActionResult Create(int id)
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            SuppliersModel supplier = _supplierRepositorio.searchForId(id);
            return View(supplier);
        }
        public IActionResult Delete(int id)
        {
            _supplierRepositorio.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult ConfirmDelete(int id)
        {
            SuppliersModel supplier = _supplierRepositorio.searchForId(id);
            return View(supplier);
        }

        [HttpPost]
        public IActionResult Create(SuppliersModel supplier)
        {
            supplier.QrCode = "%" + supplier.CNPJ + "%-" + supplier.CEP + "%" + "/CAD." + supplier.RegistrationDay + '%';
            _supplierRepositorio.add(supplier);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Change(SuppliersModel supplier)
        {
            _supplierRepositorio.Update(supplier);
            return RedirectToAction("Index");
        }
    }

    
}

Código/Teste Estágio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Projeto Vega";
}

<link rel="stylesheet" href="~/css/site.css" type="text/css" />

<div class="container text-center">
    <h1 class="display-4">Welcome!</h1>
    <p class="lead">Project made by Arthur.</p>
    <div class="row mt-5">
        <div class="col-md-6">
            <img id="profilePhoto" src="images/profilephoto.jpg" alt="Vega Logo" class="img-fluid rounded-circle" />
        </div>
        <div class="col-md-6">
            <div class="social-links">
                <div class="row social-item">
                    <div class="col-md-6">
                        <p> <a href="https://github.com/zagdolly" target="_blank">GitHub</a></p>
					</div>
                    <div class="col-md-6">
                        <a href="https://github.com/zagdolly" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/256/25/25231.png" alt="GitHub" class="social-icon" />
                        </a>
                    </div>
				</div>
                <div class="row social-item">
                    <div class="col-md-6">
                        <a href="https://www.linkedin.com/in/arthur-zagnoli-81029723a/" target="_blank">
                            <p>LinkedIn</p>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a href="https://www.linkedin.com/in/arthur-zagnoli-81029723a/" target="_blank">
                            <img src="https://cdn-icons-png.flaticon.com/256/174/174857.png" alt="LinkedIn" class="social-icon" />
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Código/Teste Estágio/Views/Material/ConfirmDelete.cshtml
@model MaterialsModel
@{
    ViewData["Title"] = "ConfirmDelete";
}

<div class="text-center">
    <h1 class="display-4">Are you sure you want to remove @Model.Name ?</h1>
    <a role="button" class="btn btn-check" asp-controller="Material" asp-action="Index">Back</a>
    <a role="button" class="btn btn-danger" asp-route-id="@Model.Id" asp-controller="Material" asp-action="Delete">Delete</a>
</div>

Código/Teste Estágio/Views/Material/Create.cshtml
@model MaterialModel
@{
    ViewData["Title"] = "Create Material";
}



<div class="text-center">
    <h1 class="display-4">Material Creation</h1>s
    <p>A Vega Project!</p>
</div>

<br />

<form asp-controller="Material" asp-action="Create" method="post">

    <div class="mb-3 form-group">
        <label for="Name" class="form-label fw-bolder">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Type the Material's Name" required>
    </div>
           
    <div class="mb-3 form-group">
        <label for="Description" class="form-label fw-bolder">Description</label>
        <input type="text" asp-for="Description" class="form-control" placeholder="Type the Material's Description" required>
    </div>

    <div class="mb-3 form-group">
        <label for="Code" class="form-label fw-bolder">Code</label>
        <input type="text" asp-for="Code" class="form-control" placeholder="Type the Material's Code" required>
    </div>

    <div class="mb-3 form-group">
        <label for="FiscalCode" class="form-label fw-bolder">FiscalCode</label>
        <input type="text" asp-for="FiscalCode" class="form-control" placeholder="Type the Material's Fiscal Code" required>
    </div>

    <div class="mb-3 form-group">
        <label for="Specie" class="form-label fw-bolder">Specie</label>
        <input type="text" asp-for="Specie" class="form-control" placeholder="Type the Material's Specie" required>
    </div>

    <div class="mb-3 form-control">
        <label for="Supplier" class="form-label fw-bolder">Supplier</label>
        <select asp-for="SupplierId" id="supplierSelect" class="form-control" required>
            <option value="" selected disabled>Choose a Supplier</option>
            @if (Model.ListaSuppliers != null)
            {
                @foreach (var item in Model.ListaSuppliers)
                {
                    <option value="@item.Id" data-description="@item.toString()">@item.Name</option>
                }
            }
        </select>
        <div class="invalid-feedback">Please select a valid supplier.</div>
    </div>


    <div class="mb-3 form-group">
        <label for="CreatedBy" class="form-label fw-bolder">CreatedBy</label>
        <input type="text" asp-for="CreatedBy" class="form-control" placeholder="Type the Your Name" required>
    </div>

    <button type="submit" class="btn btn-success">Add</button>
    <a role="button" class="btn btn-secondary" asp-controller="Home" asp-action="Index" >Back</a>
</form>

Código/Teste Estágio/Views/Material/Edit.cshtml
@model MaterialsModel
@{
    ViewData["Title"] = "Edit Material";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Supplier Editor!</h1>
    <p>A Vega Project!</p>
</div>

<br />

<form asp-controller="Material" asp-action="Change" method="post">

    <input type="hidden" asp-for="Id" />

    <div class="mb-3 form-group">
        <label for="name" class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Type the Material's Name" required>
    </div>

    <div class="mb-3 form-group">
        <label for="code" class="form-label">Codigo</label>
        <input type="text" asp-for="Code" class="form-control" placeholder="Type the Material's Code" required>
    </div>


    <div class="mb-3 form-group">
        <label for="description" class="form-label">Description</label>
        <input type="text" asp-for="Description" class="form-control" placeholder="Type the Material's Description" required>
    </div>

    <div class="mb-3 form-group">
        <label for="fiscalCode" class="form-label">Fiscal Code</label>
        <input type="text" asp-for="FiscalCode" class="form-control" placeholder="Type the Material's Fical Code" required>
    </div>

    <div class="mb-3 form-group">
        <label for="specie" class="form-label">Specie</label>
        <input type="text" asp-for="Specie" class="form-control" placeholder="Type the Material's Specie" required>
    </div>

    <div class="mb-3 form-group">
        <label for="specie" class="form-label">Your Name</label>
        <input type="text" asp-for="UpdatedBy" class="form-control" placeholder="Type Your Name" required>
    </div>



    <button type="submit" class="btn btn-success">Update</button>
    <a role="button" class="btn btn-secondary" asp-asp-controller="Material" asp-action="Index">Back</a>
</form>

Código/Teste Estágio/Views/Material/Index.cshtml
@model List<MaterialsModel>
@{
    ViewData["Title"] = "Materials";
}

<div class="text-center">
    <h1 class="display-4">Materials List</h1>
    <p>a Vega Project.</p>
</div>

<br />
<div class="text-center">
    <div class="d-grip gap-2 d-md-flex justify-content-md-start">
        <a role="button" class="btn btn-success" asp-asp-controller="Material" asp-route-supplierId="@ViewBag.SupplierId" asp-action="Create">Add New Material</a>
    </div>
<br />

<div>
        <table id="myTable" class="table text-left">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Code</th>
                <th scope="col">FiscalCode</th>
                <th scope="col">Supplier</th>
                <th scope="col">Specie</th>
                <th scope="col">CreatedAt</th>
                <th scope="col">CreatedBy</th>
                <th scope="col">UpdatedAt</th>
                <th scope="col">UpdatedBy</th>
                <th scope="col">Options</th>
            </tr>
        </thead>
            <tbody>
                @if (Model != null && Model.Any())
                {
                    foreach (MaterialsModel material in Model)
                    {
                        <tr>
                            <td>@material.Name</td>
                            <td>@material.Description</td>
                            <td>@material.Code</td>
                            <td>@material.FiscalCode</td>
                            <td>@material.Supplier</td>
                            <td>@material.Specie</td>
                            <td>@material.CreatedAt</td>
                            <td>@material.CreatedBy</td>
                            <td>@material.UpdatedAt</td>
                            <td>@material.UpdatedBy</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="basic example">
                                    <a role="button" class="btn btn-primary" asp-route-id="@material.Id" asp-controller="Material" asp-action="Edit">Edit</a>
                                    <a role="button" class="btn btn-danger" asp-route-id="@material.Id" asp-controller="Material" asp-action="ConfirmDelete">Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                }

            </tbody>
    </table>
</div>

Código/Teste Estágio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teste_Estágio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Teste_Estágio.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet"> 
</head>
<body class="d-flex flex-column" id="NavBar">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vega</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Material" asp-action="Index">Materials</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; 2024 - Teste Estágio Vega - Arthur Martins Zagnoli Silva
            <br/>
            <div class="link">
                <a href="https://www.linkedin.com/in/arthur-zagnoli-81029723a/">LinkedIn</a>
                <br />
                <a href="https://github.com/zagdolly">GitHub</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>    
    <script src="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Código/Teste Estágio/Views/Supplier/ConfirmDelete.cshtml
@model SuppliersModel
@{
    ViewData["Title"] = "Delete";
}

<div class="text-center">
    <h1 class="display-6">Are you sure you want to remove "@Model.Name" ?</h1>
    <a role="button" class="btn btn-check" asp-controller="Supplier" asp-action="Index">Back</a>
    <a role="button" class="btn btn-danger" asp-route-id="@Model.Id" asp-controller="Supplier" asp-action="Delete">Delete</a>
</div>

Código/Teste Estágio/Views/Supplier/Create.cshtml
@model SuppliersModel
@{
    ViewData["Title"] = "Create Supplier";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Supplier Creation!</h1>
    <p>A Vega Project!</p>
</div>

<br />

<form asp-controller="Supplier" asp-action="Create" method="post">


    <div class="mb-3 form-group">
        <label for="name" class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Type the Supplier's Name" required>
    </div>    

    <div class="mb-3 form-group">
        <label for="description" class="form-label">Description</label>
        <input type="text" asp-for="Description" class="form-control" placeholder="Type the Material's Description" required>
    </div>   

    <div class="mb-3 form-group">
        <label for="CNPJ" class="form-label">CNPJ</label>
        <input type="text" asp-for="CNPJ" class="form-control" placeholder="Type the Supplier's CNPJ'" required>
    </div>

    <div class="mb-3 form-group">
        <label for="CEP" class="form-label">CEP</label>
        <input type="text" asp-for="CEP" class="form-control" placeholder="Type the Supplier's CEP'" required>
    </div>

    <div class="mb-3 form-group">
        <label for="address" class="form-label">Address</label>
        <input type="text" asp-for="Address" class="form-control" placeholder="Type the Supplier's Address" required>
    </div>
    

    <div class="mb-3 form-group">
        <label for="RegistrationDay" class="form-label">Registration Day</label>
        <input type="text" asp-for="RegistrationDay" class="form-control" placeholder="Type the Supplier's Registration Day" required>
    </div>

    
    
    <button type="submit" class="btn btn-success">Add</button>
    <a role="button" class="btn btn-secondary" asp-asp-controller="Supplier" asp-action="Index">Back</a>
</form>

Código/Teste Estágio/Views/Supplier/Edit.cshtml
@model SuppliersModel
@{
    ViewData["Title"] = "Edit Supplier";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Supplier Editor!</h1>
    <p>A Vega Project!</p>
</div>

<br />

<form asp-controller="Supplier" asp-action="Change" method="post">

    <input type="hidden" asp-for="Id" />

    <div class="mb-3 form-group">
        <label for="name" class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Type the Supplier's Name" required>
    </div>    

    <div class="mb-3 form-group">
        <label for="description" class="form-label">Description</label>
        <input type="text" asp-for="Description" class="form-control" placeholder="Type the Material's Description" required>
    </div>   

    <div class="mb-3 form-group">
        <label for="address" class="form-label">Address</label>
        <input type="text" asp-for="Address" class="form-control" placeholder="Type the Supplier's Address" required>
    </div>

    <div class="mb-3 form-group">
        <label for="CEP" class="form-label">CEP</label>
        <input type="text" asp-for="CEP" class="form-control" placeholder="Type the Supplier's CEP'" required>
    </div>

    <div class="mb-3 form-group">
        <label for="CNPJ" class="form-label">CNPJ</label>
        <input type="text" asp-for="CNPJ" class="form-control" placeholder="Type the Supplier's CNPJ'" required>
    </div>



    <button type="submit" class="btn btn-success">Update</button>
    <a role="button" class="btn btn-secondary" asp-asp-controller="Supplier" asp-action="Index">Back</a>
</form>

Código/Teste Estágio/Views/Supplier/Index.cshtml
@model List<SuppliersModel>
@{
    ViewData["Title"] = "Suppliers";
}

<div class="text-center">
    <h1 class="display-4">Suppliers List</h1>
    <p>a Vega Project.</p>
</div>

<div class="d-grip d-md-flex justify-content-md-end p-2">
    <a role="button" class="btn btn-success" asp-asp-controller="Supplier" asp-action="Create">Add New Supplier</a>
</div>

<div class="text-center">
    
    <table id="myTable" class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Address</th>
                <th scope="col">CEP</th>
                <th scope="col">Registration Day</th>
                <th scope="col">Options</th>
            </tr>
        </thead>
        <tbody>

			@if (Model != null && Model.Any())
			{
				foreach (SuppliersModel supplier in Model)
				{
                    <tr class="mb-2">
                        <th>@supplier.Id</th>
                        <td>@supplier.Name</td>
                        <td>@supplier.Description</td>
                        <td>@supplier.CNPJ</td>
                        <td>@supplier.Address</td>
                        <td>@supplier.CEP</td>
                        <td>@supplier.RegistrationDay</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="basic example">
                                <a  role="button" class="btn btn-primary" asp-route-id="@supplier.Id" asp-controller="Supplier" asp-action="Edit">Edit</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@supplier.Id" asp-controller="Supplier" asp-action="ConfirmDelete">Delete</a>                                    
                            </div>
                        </td>
                    </tr>
					
				}
            }
                
        </tbody>
    </table>

    
    
</div>